### ISSUE TITLE
AttributeError: 'module' object has no attribute 'QuerySelect'

### ISSUE THREAD

**Issue by rlam3** [marshmallow-code/flask-marshmallow#37]
When I upgraded from 0.6.0 to 0.6.2 this is the error I'm getting... 

```
AttributeError: 'module' object has no attribute 'QuerySelect'
```

**Comment by rlam3** [comment]
Uninstall Flask-Marshmallow
Uninstall marshmallow-sqlalchemy
Uninstall marshmallow
Reinstall Flask-Marshmallow 
Reinstall marshmallow-sqlalchemy
